name: actions

on: [push, pull_request] # 触发事件

jobs:
  bt-product-release:
    if: ${{ github.ref == 'refs/heads/main' }}  # 检测main分支是否有更新
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 # pull代码到运行服务器上
    - name: Login to Aliyun Container Registry (ACR)
      uses: aliyun/acr-login@v1 # 使用阿里云镜像服务action
      with:
        login-server: registry.cn-shenzhen.aliyuncs.com/autoyun/autoimages # 务必正确填写镜像容器服务的登录地址
        region-id: cn-shenzhen # 务必正确填写镜像容器服务的登录地址
        username: "${{ secrets.USERNAME }}" # 引用GitHub repo设置的镜像容器服务用户名
        password: "${{ secrets.PASSWORD}}" # 引用GitHub repo设置的镜像容器服务密码
    - name: Build and Push Docker Image
      env:
        IMAGE_TAG: ${{ github.sha }} # 用于标记容器版本号
      run: |
        docker build . --file Dockerfile --tag registry.cn-shenzhen.aliyuncs.com/autoyun/autoimages:$IMAGE_TAG
        docker push registry.cn-shenzhen.aliyuncs.com/autoyun/autoimages:$IMAGE_TAG
